### ISSUE TITLE
AY48!

### ISSUE THREAD

**Issue by Engraulis** [NEO-SPECTRUMAN/NSID_Emu#1]
Вот чем маятся ерундой с этим мерзким SID-ом, лучше б AY48 дописал.

Убрать щелчки при увеличении/уменьшении громкости тона на единицу.
Выровнять шум дискретизации - чтобы был равномерно белый, пусть даже в ущерб соотношению сигнал/шум.
Мож вовсе сделать 2-х канальную версию - выводить только самые громкие/яркие звуки.

**Comment by NEO-SPECTRUMAN** [comment]
> Вот чем маятся ерундой с этим мерзким SID-ом, лучше б AY48 дописал.

это гафно написано во времена писания в асме emuzwin-а
и состоит из тон гофнокода большая часть из которого для компиляции в 1 емузвиновский сразный проход...
и теперь привести этот код к поддерживаемому виду не просто и не интересно
я делал попытки 3 4
и так и не доделол...

проще написать заново
а мне это не интересно
качество намного не поднять...

**Comment by NEO-SPECTRUMAN** [comment]
в принципе и сидом я не занимаюсь
в текущей версии в упор нет места
и для любых правок надо вышкребать лишние байты

для новой АТМ онли версии еще нету всех нужных "технологи"
времени и желания
